### ISSUE TITLE
Minikube tunnel command needs some clarification

### ISSUE THREAD

**Issue by sushmarchandran** [iter8-tools/iter8-kfserving#22]
**Description:**
In the iter8 kfserving instructions, although `minikube tunnel --cleanup` is Step 2, I have had to come back to the tab after executing Step 4 on multiple occasions to provide a password.

We could consider modifying the instructions a little bit (either move Step 2 to after Step 4 or ask the users to go back to the tab after Step 4 to provide their password).

**Documentation links:**

**Comment by sriumcp** [comment]
This is now done. Minikube tunnel is now created after istio-ingress is created, so the problem is solved.
