### ISSUE TITLE
Try out minikube with and without Docker driver

### ISSUE THREAD

**Issue by sushmarchandran** [iter8-tools/iter8-kfserving#23]
**Description:**
Experiment with (and without) `minikube tunnel -- cleanup` command with a combination of different drivers apart from Docker and update the instructions accordingly.

**Documentation links:**

**Comment by sriumcp** [comment]
We will go with docker driver for quickstart instructions for now... If need be, we can refer to kfserving instructions (for setting INGRESS HOST, IP and SERVICE HOSTNAME) subsequently.
